### ISSUE TITLE
Load historical transactions

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-explorer#1]
How much of an effort is it to load historical transactions? iirc, we need to get some sort of back end in place that will serve all the data, right? We discussed a few options, can we list them here to start with. Later we can decide which route we take.

**Comment by fazo96** [comment]
These are the currently implemented ways to discover review records in Service Nodes:

- listen for review records being created right now

These are the ones we can implement in Service Nodes

- when discovering a review record the customer orbitDb is currently seeded for review updates. We could also use it to look for new reviews
- crawl blockchain transactions and check if there is a multihash in op_return. Of course this process can be filtered by only checking transaction relevant to given addresses, for example we take the vendor address from PoPRs and crawl their transactions on the blockchain to look for other Chlu data

We could also make a search field in the Explorer UI where you can paste a multihash for a review record, transaction ID or a wallet address and the explorer can check it out and discover the relevant reviews.

### Long term

If we are still using orbitDb we can create a custom store that acts like an index with all the review records and their associated transaction on the blockchain, then we can have every service node write to this but only accept writes after they have been validated and confirmed to be correct Chlu data.

This probably needs forking ObitDB to implement the validation logic (we just need to expose a hook for custom validation), and since we are there we can also use it to store review updates and then we will have the previously discussed single-database architecture for Chlu data.

This way every service node could have easy access to the history just by following backpointers all the way back, or it could keep only the recent entries and only replicate recent data.
